name: CI
on: [push]
jobs:
  linters:
    name: Linters
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Run linters
        run: |
          bundle install |
          bundler exec rubocop --parallel
      - name: Prettify code
        uses: creyD/prettier_action@v4.2
        with:
          # This part is also where you can pass other options, for example:
          prettier_options: --write **/*.{js,md}
      - name: Run security checks
        run: |
          bin/bundler-audit --update
          bin/bundler exec brakeman -q -w2
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12
        ports: ['5432:5432']
        env:
          POSTGRES_DB: questionanswer_test
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
      - name: Install dependencies
        run: |
          sudo apt-get -yqq install libpq-dev
          gem install bundler
      - name: Install gems
        run: |
          bundle install --jobs 4 --retry 3
      - name: Setup database
        env:
          DATABASE_URL: "postgres://postgres:postgres@localhost:5432/questionanswer_test"
          RAILS_ENV: test
          DISABLE_SPRING: 1
        run: bundle exec rails db:prepare
      - name: Run tests
        env:
          DATABASE_URL: "postgres://postgres:postgres@localhost:5432/questionanswer_test"
          RAILS_ENV: test
          DISABLE_SPRING: 1
        run: bundle exec rails test
